# Generated by Django 3.0.8 on 2020-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200816_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=100)),
                ('account_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
