# Generated by Django 3.0.8 on 2020-08-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.register'),
        ),
    ]
