# Generated by Django 3.0.8 on 2020-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200817_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
