# Generated by Django 3.0.8 on 2020-08-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200818_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_color',
            field=models.CharField(default='#ffffff', max_length=8),
        ),
    ]
