# Generated by Django 3.0.8 on 2020-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_post_blog_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
