# Generated by Django 3.0.8 on 2020-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
