# Generated by Django 3.0.8 on 2020-08-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200829_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='theme',
        ),
    ]
